Adding fec docs
RedHatInsights/frontend-components pull request #1504
Opened 2022-04-08 00:16 UTC by arivepr

Adding main FEC documentation to docs page.

2022-04-08 06:55 UTC, Hyperkid123 commented on packages/docs/pages/fec/index.md
> +              '@patternfly/react-core': {
Can you delete the react-core example. We only use the one for icons.

2022-04-12 07:32 UTC, Hyperkid123 commented on packages/docs/pages/fec/index.md
> +<<<<<<< HEAD
You have some unresolved merge conflicts

2022-04-19 07:04 UTC, Hyperkid123 requested changes
@arivepr you till have git merge conflict characters in the [packages/docs/pages/fec/index.md](https://github.com/RedHatInsights/frontend-components/pull/1504/files#diff-a90130f5fab033de2dedf63f2a9fbe0b1b60d0e3a12f666367bbb5da819c8334) file .

2022-04-19 13:42 UTC, arivepr commented
> @arivepr you till have git merge conflict characters in the [packages/docs/pages/fec/index.md](https://github.com/RedHatInsights/frontend-components/pull/1504/files#diff-a90130f5fab033de2dedf63f2a9fbe0b1b60d0e3a12f666367bbb5da819c8334) file .

Don't know what happened there, should be good now

2022-04-19 14:06 UTC, Hyperkid123 commented on packages/docs/pages/fec/index.md
> +        [
This array entry should not exist. Only the one for icons :axe:

2022-04-21 14:39 UTC, Hyperkid123 approved these changes

2022-04-21 17:06 UTC, merged