Reexport components already migrated to PF
RedHatInsights/frontend-components pull request #1764
Opened 2023-06-19 15:56 UTC by fhlavac

[RHCLOUD-26558](https://issues.redhat.com/browse/RHCLOUD-26558)

Reexported components already migrated to PF. In some cases added Red Hat specific stuff to not cause issues for the existing imports.

2023-06-21 14:23 UTC, fhlavac commented
Added eslint rule to warn about using deprecated imports
![image](https://github.com/RedHatInsights/frontend-components/assets/50696716/a26f48d4-e668-4f4b-8319-872f849ca964)

2023-06-22 05:26 UTC, karelhala reviewed
Looking good! Just a minor question.

2023-06-22 05:26 UTC, karelhala commented on packages/eslint-config/lib/rules/disallow-pf-migrated-components.js
> +        const forbiddenImports = ['ErrorBoundary', 'NotAuthorized', 'ErrorState'];
Can we move this out of the function so it's more visible and easier for us to add new deprecated values?

2023-06-22 06:43 UTC, Hyperkid123 requested changes

2023-06-22 06:43 UTC, Hyperkid123 commented on packages/components/src/ErrorBoundary/ErrorBoundary.tsx
> +import { ErrorBoundary as ErrorBoundaryPF } from '@patternfly/react-component-groups';
We should be exporting the `dist/dynamic` absolute path to preserve the module federation compatibility.

2023-06-22 11:58 UTC, Hyperkid123 approved these changes

2023-06-22 11:59 UTC, Hyperkid123 commented
@fhlavac the groups repo will be ported to pf4@5 soon. Not sure if we want to wait a little bit.

2023-06-27 07:46 UTC, karelhala approved these changes

2023-08-30 13:37 UTC, Hyperkid123 approved these changes

2023-08-30 19:14 UTC, merged